// HTTP
export const GET_CASES = "GET_CASES";
export const DELETE_CASE = "DELETE_CASE";
export const ADD_CASE = "ADD_CASE";
// ERRORS
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const AUTH_ERROR = "AUTH_ERROR";
// LOADING
export const MANAGER_LOADING = "MANAGER_LOADING";
export const MANAGER_LOADED = "MANAGER_LOADED";
// LOGIN
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
// REGISTER
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
